version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: fastapi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fastapi_network

volumes:
  mysql_data:

networks:
  fastapi_network:
